// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoEOQjm9YWHroCIOxhNrM3ZCEBEKo8ZzI',
    appId: '1:497933317607:web:32ee8172f9def0ad4e7942',
    messagingSenderId: '497933317607',
    projectId: 'running-cd5f0',
    authDomain: 'running-cd5f0.firebaseapp.com',
    storageBucket: 'running-cd5f0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7B3vEFZ97Tex_B5xRbCUqsk0RheF49SQ',
    appId: '1:497933317607:android:ce590beb6182b3b84e7942',
    messagingSenderId: '497933317607',
    projectId: 'running-cd5f0',
    storageBucket: 'running-cd5f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFOL8Dg0Y0OjckwZ3KBCUmis4kPtGtjLI',
    appId: '1:497933317607:ios:6abd67b211e8e9514e7942',
    messagingSenderId: '497933317607',
    projectId: 'running-cd5f0',
    storageBucket: 'running-cd5f0.appspot.com',
    iosClientId: '497933317607-7a9t8g98pkmql3ptgmlkq6kfrh1c3ip9.apps.googleusercontent.com',
    iosBundleId: 'com.example.running',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFOL8Dg0Y0OjckwZ3KBCUmis4kPtGtjLI',
    appId: '1:497933317607:ios:73f7dd0351ef67354e7942',
    messagingSenderId: '497933317607',
    projectId: 'running-cd5f0',
    storageBucket: 'running-cd5f0.appspot.com',
    iosClientId: '497933317607-rrqkote7nsrsqdpuegupgsb8pacn68df.apps.googleusercontent.com',
    iosBundleId: 'com.example.running.RunnerTests',
  );
}
